services:
  ########################################
  ########### REVERSE-PROXY ##############
  ########################################
  traefik:
    image: ${TRAEFIK}
    command: --api.insecure=true --providers.docker=true
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-data/traefik/traefik-conf.yml:/etc/traefik/traefik.yml
      - ./init-data/traefik/traefik-services.yml:/etc/traefik/services.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - example

  ########################################
  ############### DATABASE ###############
  ########################################
  postgresdb:
    image: ${POSTGRES}
    container_name: postgresdb
    command: [-cmax_prepared_transactions=100]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-data/db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "traefik.http.services.postgresdb.loadbalancer.server.port=5432"
      - "traefik.http.routers.postgresdb.rule=Host(`postgresdb`)"
    networks:
      - example

  pgadmin:
    image: ${PGADMIN}
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    volumes:
      - ./init-data/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      postgresdb:
        condition: service_healthy
    labels:
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin`)"
    networks:
      - example
    profiles:
      - all

volumes:
  postgres:

networks:
  example: