quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://postgresdb:5432/cap-homework?sslmode=disable}
%dev.quarkus.datasource.username=${DB_USER:cap-homework}
%dev.quarkus.datasource.password=${DB_PWD:cap-homework}

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.multitenant=none
quarkus.hibernate-orm.jdbc.timezone=UTC
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.validate-on-migrate=true